//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuGiao
    {
        public int MaPG { get; set; }
        public int MaNhomTB { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual NhomThietBi NhomThietBi { get; set; }
        public virtual PhieuGiao PhieuGiao { get; set; }
    }
}
