//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuLyThietBi
    {
        public int MaPXLTB { get; set; }
        public int MaTB { get; set; }
        public Nullable<double> TienThuDuoc { get; set; }
    
        public virtual PhieuXuLyThietBi PhieuXuLyThietBi { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
