//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanTriThietBiEntities : DbContext
    {
        public QuanTriThietBiEntities()
            : base("name=QuanTriThietBiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHopDongNhapHang> ChiTietHopDongNhapHangs { get; set; }
        public virtual DbSet<ChiTietPhieuGiao> ChiTietPhieuGiaos { get; set; }
        public virtual DbSet<ChiTietPhieuXuLyThietBi> ChiTietPhieuXuLyThietBis { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<HopDongNhapHang> HopDongNhapHangs { get; set; }
        public virtual DbSet<LoaiThietBi> LoaiThietBis { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhomThietBi> NhomThietBis { get; set; }
        public virtual DbSet<PhieuChuyenThietBi> PhieuChuyenThietBis { get; set; }
        public virtual DbSet<PhieuGiao> PhieuGiaos { get; set; }
        public virtual DbSet<PhieuXuLyThietBi> PhieuXuLyThietBis { get; set; }
        public virtual DbSet<ThietBi> ThietBis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
