//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChuyenThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuChuyenThietBi()
        {
            this.ThietBis = new HashSet<ThietBi>();
        }
    
        public int MaPCTB { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> MaDV_Giao { get; set; }
        public Nullable<int> MaDV_Nhan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual DonVi DonVi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThietBi> ThietBis { get; set; }
    }
}
