//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuLyThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuLyThietBi()
        {
            this.ChiTietPhieuXuLyThietBis = new HashSet<ChiTietPhieuXuLyThietBi>();
        }
    
        public int MaPXLTB { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> QuyetDinh { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuXuLyThietBi> ChiTietPhieuXuLyThietBis { get; set; }
    }
}
