//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi()
        {
            this.ChiTietPhieuXuLyThietBis = new HashSet<ChiTietPhieuXuLyThietBi>();
            this.PhieuChuyenThietBis = new HashSet<PhieuChuyenThietBi>();
        }
    
        public int MaTB { get; set; }
        public Nullable<System.DateTime> NamSD { get; set; }
        public Nullable<double> TiLeKhauHao { get; set; }
        public Nullable<double> GiaTriSuDung { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> MaNhomTB { get; set; }
        public Nullable<int> MaDV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuXuLyThietBi> ChiTietPhieuXuLyThietBis { get; set; }
        public virtual DonVi DonVi { get; set; }
        public virtual NhomThietBi NhomThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuChuyenThietBi> PhieuChuyenThietBis { get; set; }
    }
}
